---
abstract: 'Base class and script for getting of dist from CPAN.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  File::Spec::Functions: 0
  Test::LWP::UserAgent: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CPAN-Get
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  Error::Pure: 0
  Exporter: 0
  Getopt::Std: 0
  IO::Barf: 0
  LWP::UserAgent: 0
  Menlo::Index::MetaCPAN: 0
  Readonly: 0
  URI::cpan: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-CPAN-Get/issues
  homepage: https://github.com/michal-josef-spacek/App-CPAN-Get
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-CPAN-Get
version: '0.09'
